### ISSUE TITLE
Issue with MergeLinkedList.java

### ISSUE THREAD

**Issue by mayankmukherjee21** [officialdharam/techieme#1]
Issue with MergeLinkedList.java
Try sorting this two LL , not getting correct result.
(1, 7, 8);
(3, 6, 9);

**Comment by officialdharam** [comment]
Thank you for pointing that out. 
This was an old code. Please check the correct code which is https://github.com/officialdharam/techieme/blob/master/linkedlist/MergeLL.java

I will delete the old class. Thanks a lot for your inputs.

**Comment by officialdharam** [comment]
This issue was fixed on 4th of August. Fixed the code and provided the link for the correct code.
